import type { EnvlessEnvMap } from '@/envless/ts/Types'

import { chmodSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { envlessBootstrap } from '@/envless/lib/Constants'
import EncodeValue from '@/envless/EncodeValue'

const WriteEnvFile = (
    target: string,
    map: EnvlessEnvMap,
    preserved: string[]
): string => {
    const path = resolve(process.cwd(), target)
    const lines: string[] = []

    if (preserved.length > 0) {
        lines.push('# Envless credentials, kept across runs.')

        for (const line of preserved) lines.push(line)
    }

    lines.push('# Generated by the envless script. Do not edit these by hand.')

    for (const name of Object.keys(map).sort())
        lines.push(`${name}=${EncodeValue(name, map[name])}`)

    writeFileSync(path, `${lines.join('\n')}\n`, {
        mode: envlessBootstrap.ENV_FILE_MODE
    })
    chmodSync(path, envlessBootstrap.ENV_FILE_MODE)

    return path
}

export default WriteEnvFile