// Generated by envless, do not edit by hand.
// Run `envless types` to regenerate.

declare global {
    namespace NodeJS {
        interface ProcessEnv {
            AUTH_ACCESS_TOKEN_SECRET: string
            AUTH_REFRESH_TOKEN_SECRET: string
            CLOUDFLARE_ACCESS_KEY_ID: string
            CLOUDFLARE_S3_EU_ENDPOINT: string
            CLOUDFLARE_SECRET_ACCESS_KEY: string
            CLOUDFLARE_TOKEN_VALUE: string
            ENV: string
            HOST: string
            MONGO_URI: string
            ONESIGNAL_API_KEY: string
            ONESIGNAL_APP_ID: string
            ONESIGNAL_REST_API_URL: string
            ORIGINS: string
            PORT: string
            RESEND_API_KEY: string
            RESEND_SEGMENT_ID: string
            SENT_API_KEY: string
            SENT_TEMPLATE_ID: string
        }
    }
}

declare module '@goenvless/env/server' {
    interface EnvlessServerEnv {
        AUTH_ACCESS_TOKEN_SECRET: string
        AUTH_REFRESH_TOKEN_SECRET: string
        CLOUDFLARE_ACCESS_KEY_ID: string
        CLOUDFLARE_S3_EU_ENDPOINT: string
        CLOUDFLARE_SECRET_ACCESS_KEY: string
        CLOUDFLARE_TOKEN_VALUE: string
        ENV: string
        HOST: string
        MONGO_URI: string
        ONESIGNAL_API_KEY: string
        ONESIGNAL_APP_ID: string
        ONESIGNAL_REST_API_URL: string
        ORIGINS: string
        PORT: string
        RESEND_API_KEY: string
        RESEND_SEGMENT_ID: string
        SENT_API_KEY: string
        SENT_TEMPLATE_ID: string
    }
}

export {}