// Generated by envless, do not edit by hand.
// Run `envless types` to regenerate.

declare global {
    namespace NodeJS {
        interface ProcessEnv {
            AUTH_ACCESS_TOKEN_SECRET: string
            AUTH_REFRESH_TOKEN_SECRET: string
            ENV: string
            OPENEMAIL_ADMIN: string
            OPENEMAIL_API_KEY: string
            OPENEMAIL_FROM: string
            ORIGINS: string
            SENT_API_KEY: string
            SENT_TEMPLATE_ID: string
        }
    }
}

declare module '@goenvless/env/server' {
    interface EnvlessServerEnv {
        AUTH_ACCESS_TOKEN_SECRET: string
        AUTH_REFRESH_TOKEN_SECRET: string
        ENV: string
        OPENEMAIL_ADMIN: string
        OPENEMAIL_API_KEY: string
        OPENEMAIL_FROM: string
        ORIGINS: string
        SENT_API_KEY: string
        SENT_TEMPLATE_ID: string
    }
}

export {}